<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SmartParentingAssistant.Domain\SmartParentingAssistant.Domain.csproj" />
    <ProjectReference Include="..\SmartParentingAssistant.Shared\SmartParentingAssistant.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.TextAnalytics" Version="5.3.0" />
    <PackageReference Include="Azure.Core" Version="1.50.0" />
    <PackageReference Include="FluentValidation" Version="12.1.0" />
    <PackageReference Include="MediatR" Version="13.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Behaviors\" />
    <Folder Include="Features\Moods\Commands\" />
    <Folder Include="Features\Tips\Queries\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
